passthrough_copy = [
    "*.css",
    "**/*.png",
    "assets/**/*",
    "favicon/*",
    ".nojekyll",
    "CNAME",
    "404.html",
]
post_processing_typ = ['python', 'scripts/post-process.py']
file_listing = "include-data"
