passthrough_copy = [
    "*.css",
    "**/*.png",
    "**/*.jpg",
    "**/*.html",
    "assets/**/*",
    "favicon/*",
    ".nojekyll",
    "CNAME",
]
post_processing_typ = ["python", "$PROJECT_ROOT/scripts/post-process.py"]
file_listing = "include-data"
file_listing_extra_args = ["--ignore-system-fonts"]
compilation_extra_args = ["--ignore-system-fonts"]
disable_incremental = true
